Repository hmcts/et-pet-ccd-export, pull requests merged in 2024-02, with the labels that each got.

#365 (RST-6289) Upgraded nokogiri (security issue)
  Gemfile.lock
Labels: ns:et-pet, prd:et-pet, rel:et-pet-ccd-export-pr-365

#367 RST-5591 update et_fake_ccd to 3.0.1
  Gemfile.lock
Labels: ns:et-pet, prd:et-pet, rel:et-pet-ccd-export-pr-367

#368 (RST-5509) Added auto recovery from error 409 conflict
  Gemfile
  Gemfile.lock
  app/services/export_claim_service.rb
  app/services/export_multiple_claims_service.rb
  spec/factories/claimant_factory.rb
  spec/integration/create_claim_multiples_spec.rb
  spec/integration/create_claim_spec.rb
  spec/support/drain_all_our_sidekiq_jobs.rb
  spec/support/with_sidekiq_error_capturing.rb
Labels: ns:et-pet, prd:et-pet, rel:et-pet-ccd-export-pr-368

#370 Rst 6376
  Gemfile
  Gemfile.lock
Labels: ns:et-pet, prd:et-pet, rel:et-pet-ccd-export-pr-370
